
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FilterService", targetNamespace = "http://some/", wsdlLocation = "http://localhost:8090/filter?wsdl")
public class FilterService
    extends Service
{

    private final static URL FILTERSERVICE_WSDL_LOCATION;
    private final static WebServiceException FILTERSERVICE_EXCEPTION;
    private final static QName FILTERSERVICE_QNAME = new QName("http://some/", "FilterService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/filter?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILTERSERVICE_WSDL_LOCATION = url;
        FILTERSERVICE_EXCEPTION = e;
    }

    public FilterService() {
        super(__getWsdlLocation(), FILTERSERVICE_QNAME);
    }

    public FilterService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILTERSERVICE_QNAME, features);
    }

    public FilterService(URL wsdlLocation) {
        super(wsdlLocation, FILTERSERVICE_QNAME);
    }

    public FilterService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILTERSERVICE_QNAME, features);
    }

    public FilterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FilterService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Filter
     */
    @WebEndpoint(name = "FilterPort")
    public Filter getFilterPort() {
        return super.getPort(new QName("http://some/", "FilterPort"), Filter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Filter
     */
    @WebEndpoint(name = "FilterPort")
    public Filter getFilterPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://some/", "FilterPort"), Filter.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILTERSERVICE_EXCEPTION!= null) {
            throw FILTERSERVICE_EXCEPTION;
        }
        return FILTERSERVICE_WSDL_LOCATION;
    }

}
