
package client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Filter", targetNamespace = "http://some/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Filter {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<client.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "byDate", targetNamespace = "http://some/", className = "client.ByDate")
    @ResponseWrapper(localName = "byDateResponse", targetNamespace = "http://some/", className = "client.ByDateResponse")
    @Action(input = "http://some/Filter/byDateRequest", output = "http://some/Filter/byDateResponse")
    public List<Person> byDate(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<client.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "byLastName", targetNamespace = "http://some/", className = "client.ByLastName")
    @ResponseWrapper(localName = "byLastNameResponse", targetNamespace = "http://some/", className = "client.ByLastNameResponse")
    @Action(input = "http://some/Filter/byLastNameRequest", output = "http://some/Filter/byLastNameResponse")
    public List<Person> byLastName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
